name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout the repo
      - uses: actions/setup-go@v2 # setup go
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go